### PR TITLE
Sardonyx Website Improvements

### PR DESCRIPTION
**Pull request by cursorweb**
changed the navbar so it is slightly better on smaller screens with an 'overflow' image effect. Links have been slightly changed for a better look, along with some code edits. I also added a `README.md`.

### CODE REVIEW

**Comment by ghost** [comment]
Hmmm, I'm afraid these changes are too minor to merge. If you would like to make more meaningful changes, I'd be happy to accept this PR - if not, let me know and I will close it.

**Comment by cursorweb** [comment]
ok

**Comment by cursorweb** [comment]
ok, I added incremental updates.

**Comment by ghost** [comment]
*sighs* why not

**Pull request merged**
